SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `TESIS` ;
CREATE SCHEMA IF NOT EXISTS `TESIS` DEFAULT CHARACTER SET latin1 ;
USE `TESIS` ;

-- -----------------------------------------------------
-- Table `TESIS`.`TTIPOUSUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESIS`.`TTIPOUSUARIOS` ;

CREATE  TABLE IF NOT EXISTS `TESIS`.`TTIPOUSUARIOS` (
  `CTIPOUSUARIO` VARCHAR(255) NOT NULL ,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL ,
  `FDESDE` DATETIME NULL DEFAULT NULL ,
  PRIMARY KEY (`CTIPOUSUARIO`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TESIS`.`TROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESIS`.`TROLES` ;

CREATE  TABLE IF NOT EXISTS `TESIS`.`TROLES` (
  `CROL` INT(11) NOT NULL ,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL ,
  `FDESDE` DATETIME NULL DEFAULT NULL ,
  PRIMARY KEY (`CROL`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TESIS`.`TUSUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESIS`.`TUSUARIOS`;

CREATE  TABLE IF NOT EXISTS `TESIS`.`TUSUARIOS` (
  `CUSUARIO` VARCHAR(255) NOT NULL ,
  `FKFHASTA` DATETIME NOT NULL ,
  `ACTIVO` BIT(1) NULL DEFAULT NULL ,
  `FKCTIPOUSUARIO` VARCHAR(255) NULL DEFAULT NULL ,  
  `FKCROL` INT(11) NULL DEFAULT NULL ,
  `FDESDE` DATETIME NULL DEFAULT NULL ,
  `FVIGENCIADESDE` DATETIME NULL DEFAULT NULL ,
  `FVIGENCIAHASTA` DATETIME NULL DEFAULT NULL ,
  PRIMARY KEY (`CUSUARIO`,`FKFHASTA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE `TESIS`.`TUSUARIOS` ADD CONSTRAINT `fk_TUSUARIOS_1` FOREIGN KEY `fk_TUSUARIOS_1` (`FKCTIPOUSUARIO`)
REFERENCES `TTIPOUSUARIOS` (`CTIPOUSUARIO`)
ON DELETE NO ACTION
ON UPDATE NO ACTION; 

ALTER TABLE `TESIS`.`TUSUARIOS` ADD CONSTRAINT `fk_TUSUARIOS_2` FOREIGN KEY `fk_TUSUARIOS_2` (`FKCROL`)
REFERENCES `TROLES` (`CROL`)
ON DELETE NO ACTION
ON UPDATE NO ACTION; 


-- -----------------------------------------------------
-- Table `TESIS`.`TTIPOAUTORIZACIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESIS`.`TTIPOAUTORIZACIONES` ;

CREATE  TABLE IF NOT EXISTS `TESIS`.`TTIPOAUTORIZACIONES` (
  `CTIPOAUTORIZACION` VARCHAR(255) NOT NULL ,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL ,
  `FDESDE` DATETIME NULL DEFAULT NULL ,
  PRIMARY KEY (`CTIPOAUTORIZACION`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TESIS`.`TESTATUSAUTORIZACIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESIS`.`TESTATUSAUTORIZACIONES` ;

CREATE  TABLE IF NOT EXISTS `TESIS`.`TESTATUSAUTORIZACIONES` (
  `CESTATUSAUTORIZACION` VARCHAR(255) NOT NULL ,
  `DESCRIPCION` VARCHAR(255) NULL DEFAULT NULL ,
  `FDESDE` DATETIME NULL DEFAULT NULL ,
  PRIMARY KEY (`CESTATUSAUTORIZACION`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TESIS`.`TTOKENS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESIS`.`TTOKENS` ;

CREATE  TABLE IF NOT EXISTS `TESIS`.`TTOKENS` (
  `TOKEN` VARCHAR(255) NOT NULL ,
  `FDESDE` DATETIME NULL DEFAULT NULL ,
  PRIMARY KEY (`TOKEN`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TESIS`.`TAUTORIZACIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESIS`.`TAUTORIZACIONES` ;

CREATE  TABLE IF NOT EXISTS `TESIS`.`TAUTORIZACIONES` (
  `NUMEROMENSAJE` VARCHAR(255) NOT NULL ,
  `FK2FHASTA` DATETIME NOT NULL ,
  `FKCESTATUSAUTORIZACION` VARCHAR(255) NOT NULL,
  `FKCTIPOAUTORIZACION` VARCHAR(255) NULL DEFAULT NULL ,
  `CTRANSACCION` VARCHAR(255) NOT NULL,
  `NOMBRE` VARCHAR(255) NULL DEFAULT NULL,
  `FKCUSUARIO` VARCHAR(255) NULL DEFAULT NULL ,
  `CUSUARIO_ORIGEN` VARCHAR(255) NULL DEFAULT NULL ,
  `FDESDE` DATETIME NULL DEFAULT NULL ,
  `FPROCESO` DATETIME NULL DEFAULT NULL ,
  `FKTOKEN` VARCHAR(255) NULL DEFAULT NULL ,
  `MENSAJE` VARCHAR(255) NULL DEFAULT NULL ,
  PRIMARY KEY (`NUMEROMENSAJE`, `FK2FHASTA`))
ENGINE=InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE `TESIS`.`TAUTORIZACIONES` ADD CONSTRAINT `fk_TAUTORIZACIONES_1` FOREIGN KEY `fk_TAUTORIZACIONES_1` (`FKCUSUARIO`)
REFERENCES `TUSUARIOS` (`CUSUARIO`)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE `TESIS`.`TAUTORIZACIONES` ADD CONSTRAINT `fk_TAUTORIZACIONES_2` FOREIGN KEY `fk_TAUTORIZACIONES_2` (`FKCTIPOAUTORIZACION`)
REFERENCES `TTIPOAUTORIZACIONES` (`CTIPOAUTORIZACION`)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE `TESIS`.`TAUTORIZACIONES` ADD CONSTRAINT `fk_TAUTORIZACIONES_3` FOREIGN KEY `fk_TAUTORIZACIONES_3` (`FKCESTATUSAUTORIZACION`)
REFERENCES `TESTATUSAUTORIZACIONES` (`CESTATUSAUTORIZACION`)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE `TESIS`.`TAUTORIZACIONES` ADD CONSTRAINT `fk_TAUTORIZACIONES_4` FOREIGN KEY `fk_TAUTORIZACIONES_4` (`FKTOKEN`)
REFERENCES `TTOKENS` (`TOKEN`)
ON DELETE NO ACTION
ON UPDATE NO ACTION;


-- -----------------------------------------------------
-- Table `TESIS`.`TLOGAUTORIZACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESIS`.`TLOGAUTORIZACION` ;

CREATE  TABLE IF NOT EXISTS `TESIS`.`TLOGAUTORIZACION` (
  `NUMEROMENSAJE` VARCHAR(255) NOT NULL ,
  `CESTATUSAUTORIZACION` VARCHAR(255) NOT NULL ,
  `MENSAJE_XML` LONGBLOB NULL DEFAULT NULL ,
  `ORIGEN_MENSAJE` BIT(1) NULL DEFAULT NULL ,
  PRIMARY KEY (`NUMEROMENSAJE`, `CESTATUSAUTORIZACION`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `TESIS`.`TPARAMETROSSISTEMA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESIS`.`TPARAMETROSSISTEMA` ;

CREATE  TABLE IF NOT EXISTS `TESIS`.`TPARAMETROSSISTEMA` (
  `FHASTA` DATETIME NOT NULL ,
  `CPARAMENTRO` VARCHAR(255) NOT NULL ,
  `FDESDE` DATETIME NULL DEFAULT NULL ,
  `VALOR_CADENA` VARCHAR(255) NULL DEFAULT NULL ,
  `VALOR_ENTERO` INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (`FHASTA`, `CPARAMENTRO`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TESIS`.`TUSUARIODISPOSITIVOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESIS`.`TUSUARIODISPOSITIVOS` ;

CREATE  TABLE IF NOT EXISTS `TESIS`.`TUSUARIODISPOSITIVOS` (
  `MODELO` VARCHAR(255) NOT NULL ,
  `ID` VARCHAR(255) NOT NULL ,
  `FKCUSUARIO` VARCHAR(255) NOT NULL ,
  `FHASTA` DATETIME NOT NULL ,  
  `ESTADO` VARCHAR(255) NULL DEFAULT NULL ,
  `FDESDE` DATETIME NULL DEFAULT NULL ,
  `FCONEXION` DATETIME NULL DEFAULT NULL ,
  PRIMARY KEY (`MODELO`, `ID`, `FHASTA`, `FKCUSUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE `TESIS`.`TUSUARIODISPOSITIVOS` ADD CONSTRAINT `fk_TUSUARIODISPOSITIVOS_1` FOREIGN KEY `fk_TUSUARIODISPOSITIVOS_1` (`FKCUSUARIO`)
REFERENCES `TUSUARIOS` (`CUSUARIO`)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
-- -----------------------------------------------------
-- Table `TESIS`.`TUSUARIOINFORMACIONADICIONAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESIS`.`TUSUARIOINFORMACIONADICIONAL` ;

CREATE  TABLE IF NOT EXISTS `TESIS`.`TUSUARIOINFORMACIONADICIONAL` (
  `FHASTA` DATETIME NOT NULL ,
  `FKCUSUARIO` VARCHAR(255) NOT NULL ,
  `FDESDE` DATETIME NULL DEFAULT NULL ,
  `MAIL` VARCHAR(255) NULL DEFAULT NULL ,
  `NOMBRE` VARCHAR(255) NULL DEFAULT NULL ,
  `KEYWORD` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`FHASTA`, `FKCUSUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE `TESIS`.`TUSUARIOINFORMACIONADICIONAL` ADD CONSTRAINT `fk_TUSUARIOINFORMACIONADICIONAL_1` FOREIGN KEY `fk_TUSUARIOINFORMACIONADICIONAL_1` (`FKCUSUARIO`)
REFERENCES `TUSUARIOS` (`CUSUARIO`)
ON DELETE NO ACTION
ON UPDATE NO ACTION;
-- -----------------------------------------------------
-- Table `TESIS`.`TUSUARIOPASSWORD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESIS`.`TUSUARIOPASSWORD` ;

CREATE  TABLE IF NOT EXISTS `TESIS`.`TUSUARIOPASSWORD` (
  `FHASTA` DATETIME NOT NULL ,
  `FKCUSUARIO` VARCHAR(255) NOT NULL ,
  `FCADUCIDAD` DATE NULL DEFAULT NULL ,
  `FDESDE` DATETIME NULL DEFAULT NULL ,
  `PASSWORD` VARCHAR(255) NOT NULL ,
  PRIMARY KEY (`FHASTA`, `FKCUSUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE `TESIS`.`TUSUARIOPASSWORD` ADD CONSTRAINT `fk_TUSUARIOPASSWORD_1` FOREIGN KEY `fk_TUSUARIOPASSWORD_1` (`FKCUSUARIO`)
REFERENCES `TUSUARIOS` (`CUSUARIO`)
ON DELETE NO ACTION
ON UPDATE NO ACTION;


-- -----------------------------------------------------
-- Table `TESIS`.`TSESIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESIS`.`TSESIONES` ;

CREATE  TABLE IF NOT EXISTS `TESIS`.`TSESIONES` (
  `SESIONID` VARCHAR(255) NOT NULL ,
  `CUSUARIO` VARCHAR(255) NOT NULL ,
  `FINICIO` DATETIME NOT NULL ,
  `FFIN` DATETIME NULL DEFAULT NULL ,
  PRIMARY KEY (`SESIONID`, `CUSUARIO`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
