--Transaccion 046028

delete from tcomandosmantenimiento where csubsistema='04' and ctransaccion='6028';
delete from tcomandosid where comando='com.fitbank.view.query.ObtainCheckForNotification';
insert into TCOMANDOSID (COMANDO, TIPOCOMANDO) values ('com.fitbank.view.query.ObtainCheckForNotification', 'CON');

insert into TCOMANDOSMANTENIMIENTO (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, SCOMANDO, EVENTO, COMANDO, ORDEN, USACACHE, TIPOCOMANDO, ACTIVADO, CANALESEXCLUIDOS, PARAMETRO, VERSIONCONTROL, EJECUTADOPOR) values ('04', '6028', '01', 1, 'I', 'com.fitbank.view.maintenance.bpm.GetAccountOfficial', 1, '0', 'MAN', '1', null, null, 1, 'F');
insert into TCOMANDOSMANTENIMIENTO (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, SCOMANDO, EVENTO, COMANDO, ORDEN, USACACHE, TIPOCOMANDO, ACTIVADO, CANALESEXCLUIDOS, PARAMETRO, VERSIONCONTROL, EJECUTADOPOR) values ('04', '6028', '01', 2, 'I', 'com.fitbank.bpm.command.BPMInitFlowFinish', 2, '0', 'MAN', '1', null, 'protestAuthorizationCheck', 1, 'F');
insert into TCOMANDOSMANTENIMIENTO (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, SCOMANDO, EVENTO, COMANDO, ORDEN, USACACHE, TIPOCOMANDO, ACTIVADO, CANALESEXCLUIDOS, PARAMETRO, VERSIONCONTROL, EJECUTADOPOR) values ('04', '6028', '01', 3, 'I', 'com.fitbank.view.sequence.AccountsDocumentsSequence', 3, '0', 'MAN', '1', null, null, 0, 'B');
insert into TCOMANDOSMANTENIMIENTO (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, SCOMANDO, EVENTO, COMANDO, ORDEN, USACACHE, TIPOCOMANDO, ACTIVADO, CANALESEXCLUIDOS, PARAMETRO, VERSIONCONTROL, EJECUTADOPOR) values ('04', '6028', '01', 4, 'I', 'com.fitbank.maintenance.MaintenanceImages', 4, '0', 'MAN', '1', null, null, 0, 'B');
insert into TCOMANDOSMANTENIMIENTO (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, SCOMANDO, EVENTO, COMANDO, ORDEN, USACACHE, TIPOCOMANDO, ACTIVADO, CANALESEXCLUIDOS, PARAMETRO, VERSIONCONTROL, EJECUTADOPOR) values ('04', '6028', '01', 5, 'I', 'com.fitbank.processor.maintenance.MaintenanceProcessor', 5, '0', 'MAN', '1', null, null, 1, 'B');
insert into TCOMANDOSMANTENIMIENTO (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, SCOMANDO, EVENTO, COMANDO, ORDEN, USACACHE, TIPOCOMANDO, ACTIVADO, CANALESEXCLUIDOS, PARAMETRO, VERSIONCONTROL, EJECUTADOPOR) values ('04', '6028', '01', 6, 'I', 'com.fitbank.processor.query.QueryProcessor', 6, '0', 'CON', '1', null, null, 0, 'F');
insert into TCOMANDOSMANTENIMIENTO (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, SCOMANDO, EVENTO, COMANDO, ORDEN, USACACHE, TIPOCOMANDO, ACTIVADO, CANALESEXCLUIDOS, PARAMETRO, VERSIONCONTROL, EJECUTADOPOR) values ('04', '6028', '01', 7, 'I', 'com.fitbank.view.query.ObtainCheckForNotification', 7, '0', 'CON', '1', null, null, 0, 'N');

