--//CAMBIOS A LA TABLA TCOMANDOSMANTENIMIENTO PARA ACEPTAR COMANDOS TIPO N

ALTER TABLE
    FITAUSTRO.TCOMANDOSMANTENIMIENTO DROP CONSTRAINT CKEJECUTADOPOR;
ALTER TABLE
    FITAUSTRO.TCOMANDOSMANTENIMIENTO ADD CONSTRAINT CKEJECUTADOPOR 
    CHECK (EJECUTADOPOR IS NULL OR (EJECUTADOPOR = upper(EJECUTADOPOR) AND EJECUTADOPOR IN ('B','F','A','C','D','N')))