//--DISPOSITIVO DE ESCUCHA DE NUESTRAS RESPUESTAS
delete from tdispositivo where canal='XML' AND CDISPOSITIVO='NOTIFICATION';

insert into TDISPOSITIVO (CCANAL, CDISPOSITIVO, TIPODISPOSITIVO, UNIDADLOGICA, CTERMINAL, ENPROCESO, CUSUARIO, PARAMETROS, CSERVIDORAPLICACION, CTIPOCONTROLADOR, EXCLUSIVA, ENLINEA, PARALELO, MODOEXCLUSIVO, AGRUPAMIENTO, INICIAR, VERSIONCONTROL) values ('XML', 'NOTIFICATION', 'O', null, null, '0', null, 'S#ES#localhost#30022#XX-XX-XX-XX-XX-XX#6#0#0#0#', 'UCI', 'TCRR', '1', '0', '0', '0', 'WEB', '1', 0);


//--PARAMETRIZACION PARA INTEGRACION BPM Y NOTIFICATION
DELETE FROM TCOMANDOSMANTENIMIENTO WHERE CSUBSISTEMA='01' AND CTRANSACCION='8005';
DELETE from tcomandos where comando='com.fitbank.bpm.query.NotificationInterface';
DELETE from tcomandosid where comando='com.fitbank.bpm.query.NotificationInterface';


insert into TCOMANDOSID (COMANDO, TIPOCOMANDO) values ('com.fitbank.bpm.query.NotificationInterface', 'CON');
insert into TCOMANDOS (COMANDO, TIPOCOMANDO, FHASTA, CIDIOMA, FDESDE, DESCRIPCION, VERSIONCONTROL) values ('com.fitbank.bpm.query.NotificationInterface', 'CON', TIMESTAMP '2999-12-31 00:00:00', 'ES', TIMESTAMP '2012-02-15 12:50:10', 'INTERFAZ DE COMUNICACION CON EL SERVIDOR DE NOTIFICACIONES', 0);

insert into TCOMANDOSMANTENIMIENTO (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, SCOMANDO, EVENTO, COMANDO, ORDEN, USACACHE, TIPOCOMANDO, ACTIVADO, CANALESEXCLUIDOS, PARAMETRO, VERSIONCONTROL, EJECUTADOPOR) values ('01', '8005', '01', 1, 'I', 'com.fitbank.bpm.query.MailNotification', 4, '0', 'CON', '1', null, null, 0, null);
insert into TCOMANDOSMANTENIMIENTO (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, SCOMANDO, EVENTO, COMANDO, ORDEN, USACACHE, TIPOCOMANDO, ACTIVADO, CANALESEXCLUIDOS, PARAMETRO, VERSIONCONTROL, EJECUTADOPOR) values ('01', '8005', '01', 2, 'I', 'com.fitbank.bpm.query.InstanceFlowNameGetter', 1, '0', 'CON', '1', null, null, 0, null);
insert into TCOMANDOSMANTENIMIENTO (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, SCOMANDO, EVENTO, COMANDO, ORDEN, USACACHE, TIPOCOMANDO, ACTIVADO, CANALESEXCLUIDOS, PARAMETRO, VERSIONCONTROL, EJECUTADOPOR) values ('01', '8005', '01', 3, 'I', 'com.fitbank.bpm.maintenance.PrepareNotification', 2, '0', 'CON', '1', null, 'CE', 0, null);
insert into TCOMANDOSMANTENIMIENTO (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, SCOMANDO, EVENTO, COMANDO, ORDEN, USACACHE, TIPOCOMANDO, ACTIVADO, CANALESEXCLUIDOS, PARAMETRO, VERSIONCONTROL, EJECUTADOPOR) values ('01', '8005', '01', 4, 'I', 'com.fitbank.bpm.maintenance.SaveNotification', 3, '0', 'CON', '1', null, null, 0, null);
insert into TCOMANDOSMANTENIMIENTO (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, SCOMANDO, EVENTO, COMANDO, ORDEN, USACACHE, TIPOCOMANDO, ACTIVADO, CANALESEXCLUIDOS, PARAMETRO, VERSIONCONTROL, EJECUTADOPOR) values ('01', '8005', '01', 5, 'I', 'com.fitbank.bpm.query.NotificationInterface', 5, '0', 'CON', '1', null, null, 0, null);


